// { "framework": "Weex" }
/******/ (function(modules) { // webpackBootstrap
/******/ 	// The module cache
/******/ 	var installedModules = {};

/******/ 	// The require function
/******/ 	function __webpack_require__(moduleId) {

/******/ 		// Check if module is in cache
/******/ 		if(installedModules[moduleId])
/******/ 			return installedModules[moduleId].exports;

/******/ 		// Create a new module (and put it into the cache)
/******/ 		var module = installedModules[moduleId] = {
/******/ 			exports: {},
/******/ 			id: moduleId,
/******/ 			loaded: false
/******/ 		};

/******/ 		// Execute the module function
/******/ 		modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);

/******/ 		// Flag the module as loaded
/******/ 		module.loaded = true;

/******/ 		// Return the exports of the module
/******/ 		return module.exports;
/******/ 	}


/******/ 	// expose the modules object (__webpack_modules__)
/******/ 	__webpack_require__.m = modules;

/******/ 	// expose the module cache
/******/ 	__webpack_require__.c = installedModules;

/******/ 	// __webpack_public_path__
/******/ 	__webpack_require__.p = "";

/******/ 	// Load entry module and return exports
/******/ 	return __webpack_require__(0);
/******/ })
/************************************************************************/
/******/ ([
/* 0 */
/***/ function(module, exports, __webpack_require__) {

	var __weex_template__ = __webpack_require__(1)
	var __weex_script__ = __webpack_require__(2)

	__weex_define__('@weex-component/d372cb3fbee0951d8bd9f95a84a68527', [], function(__weex_require__, __weex_exports__, __weex_module__) {

	    __weex_script__(__weex_module__, __weex_exports__, __weex_require__)
	    if (__weex_exports__.__esModule && __weex_exports__.default) {
	      __weex_module__.exports = __weex_exports__.default
	    }

	    __weex_module__.exports.template = __weex_template__

	})

	__weex_bootstrap__('@weex-component/d372cb3fbee0951d8bd9f95a84a68527',undefined,undefined)

/***/ },
/* 1 */
/***/ function(module, exports) {

	module.exports = {
	  "type": "scroller",
	  "children": [
	    {
	      "type": "div",
	      "children": [
	        {
	          "type": "text",
	          "classList": [
	            "content"
	          ],
	          "attr": {
	            "value": function () {return this.HTML_CONTENT}
	          }
	        }
	      ]
	    }
	  ]
	}

/***/ },
/* 2 */
/***/ function(module, exports) {

	module.exports = function(module, exports, __weex_require__){'use strict';

	var stream = __weex_require__('@weex-module/stream');
	var DES = __weex_require__('@weex-module/DesModule');
	var modal = __weex_require__('@weex-module/modal');
	var storage = __weex_require__('@weex-module/storage');
	var navigator = __weex_require__('@weex-module/navigator');
	var eventurl = __weex_require__('@weex-module/event');

	module.exports = {
	  data: function () {return {
	    'HTML_CONTENT': null
	  }},
	  init: function init() {},
	  created: function created() {},
	  ready: function ready() {

	    var self = this;
	    var url = "/cloud/dailies?";
	    var jsonobj = { 'page': '1', 'row': '3', 'mobileKey': '1ea20db1ca724086870f92347cf87d00' };

	    DES.getDateWithHttps(url, jsonobj, function (result) {

	      console.log(1111);
	      console.log("result jjjjjjjjj:" + result);
	      var respone = JSON.parse(result);
	      var str = respone.data[1].HTML_CONTENT;
	      console.log("result poiiiiii:" + str);
	      str = str.replace(/<br \/>/g, "\n");
	      str = str.replace("<p>", "\n");
	      str = str.replace("</p>", "\n");
	      str = str.replace("&ldquo;", "“");
	      str = str.replace("&rdquo;", "”");
	      str = str.replace("&nbsp;", " ");
	      console.log("result poiiiiii:" + str);

	      self.HTML_CONTENT = str;
	    });
	  }
	};}
	/* generated by weex-loader */


/***/ }
/******/ ]);